FROM debian:jessie
MAINTAINER me <philipp.pfaff@cargomedia.ch>

RUN '/usr/bin/apt-get update'
RUN '/usr/bin/wget -q -O - https://raw.github.com/cargomedia/puppet-packages/master/scripts/puppet-install.sh | bash'
