Vagrant.configure('2') do |config|

  config.librarian_puppet.puppetfile_dir = 'puppet'
  config.librarian_puppet.placeholder_filename = '.gitkeep'
  config.librarian_puppet.resolve_options = {:force => true}

  config.vm.provision :puppet do |puppet|
    puppet.module_path = 'puppet/modules'
    puppet.manifests_path = 'puppet/manifests'
  end




  config.vm.box = 'cargomedia/debian-8-amd64-default'
  config.vm.network :forwarded_port, guest: 22, host: 22211, id: 'ssh'
end
